### ISSUE TITLE
Using setup.py so this can be called globally

### ISSUE THREAD

**Issue by trakBan** [iaacornus/wikiterm#2]
This isnt really an issue but more of an suggestion. You might want to use setup.py so this program can be called from anywhere in the terminal.

**Comment by iaacornus** [comment]
the setup of the program is you move it from a specific and alias it in your `.bashrc`, since it is more of a script rather than a program. So for example you moved it into your `$HOME/.wikiscript/` you put `alias wiki="$HOME/.wikiscript/wikiterm/src/cli.py` and use it normally, `wiki hello`.
